apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'

        scrape_interval: 5s

        static_configs:
        - targets: ['localhost:9090']

    remote_read:
        - url: https://example.com/read
          bearer_token: <example-API-Key>
          
    remote_write:
        - url: https://example.com/write
          bearer_token: <example-API-Key>
