global:
        scrape_interval: '5s'
        evaluation_interval: '5s'
alerting:
        alertmanagers:
        - static_configs:
          - targets:
                  - alertmanager: 9093
rules_file:
        - 'rules.yaml'
scrape_configs:
        - job_name: 'prometheus'
          static_configs:
                  - targets: ['localhost:9090']
remote_read:
        - url: 'placeholder'
          bearer_token: 'placeholder'
remote_write:
        - url: 'placeholder'
          bearer_token: 'placeholder'
